### ISSUE TITLE
[REQUEST] Make a pull request on this repo from symbolic_comp_two 

### ISSUE THREAD

**Issue by dhk465** [dhk465/symbolic_comp_one#18]
**Is your feature request related to a problem? Please describe.**
We are not using [symbolic_comp_two repo](https://github.com/Slemanof/symbolic_comp_two) anymore since we can label versions in this repo.

**Describe the solution you'd like**
@Slemanof needs to create a pull request on this repo to pull all the commits from symbolic_comp_two.

**Comment by dhk465** [comment]
I solved the issue #20 and now @Slemanof can make a pull request.

**Comment by Slemanof** [comment]
Issue #18 is solved and pull request was performed.
