### ISSUE TITLE
[UPDATE] Data structure consisting of spruce tree and linden tree

### ISSUE THREAD

**Issue by ilyassakhanov** [dhk465/symbolic_comp_one#24]
## Change the Data, that Chat bot reads
Considering the fact, that spruce and linden tree were chosen as the object that are going to be scanned/described by user, the json file with the key words should be changed along side with the ParkData.clj file.

**Comment by dhk465** [comment]
So, largely it is a two parts project: **training + recognition** and **altering the current chatbot code**.

One person can alter the current chatbot structure and the rest can work on the training.

**Comment by ilyassakhanov** [comment]
As discussed with the team, there will not be another dataset containing information about spruce tree and linden tree. Thus, a new JSON file with key words and a new file along ParkData.clj won't be created.
