### ISSUE TITLE
[FEATURE]-Adding options layer to the beginning of the Chatbot

### ISSUE THREAD

**Issue by Slemanof** [dhk465/symbolic_comp_one#26]
**Is your feature request related to a problem? Please describe.**
The user has no place to ask about the tree picture or upload it.

**Describe the solution you'd like**
Adding an option at the beginning of the chat dialogue asking the user to choose weather they want parks recommendations or asking about tree type.

**Describe alternatives you've considered**
The look up tree type option could be included in the dialogue of the chatbot and promoted when keywords are mentioned such as "what is this tree" or "which type of trees is this"

**Comment by dhk465** [comment]
solved with #25
