### ISSUE TITLE
[BUG] Dependency to simple.clj

### ISSUE THREAD

**Issue by ilyassakhanov** [dhk465/symbolic_comp_one#32]
**Describe the bug**
A dependency to simple.clj can not be made due to some weird reason.The line 9 in core.clj does not behave correctly and produces an error. The error message doesn't make any sense. If the line 9 in core.clj is removed, switching namespaces becomes impossible.
[@classifier_tester](https://github.com/dhk465/symbolic_comp_one/tree/classifier_tester)
**To Reproduce**
1. Go to symbolic_comp_one
2.Do lein repl which will produce the error
3. (require 'classify.simple)
    (in-ns 'classify.simple)
     Now you've switched namespaces and can use classifier.

**Expected behaviour**
simple.clj is importing all the  functions.

**Desktop (please complete the following information):**
 - OS: [Fedora 31]
 - Leiningen Version [e.g. 2.0.0]

** List of Dependencies **
- Dependency and Version [e.g. Cortex 1.9.3]

**Comment by dhk465** [comment]
This is rather "simple".
You should not name it as [ica.example.src.classify.simple]
but [ica.simple].
Consider we do not have such path in the branch.
[ica.example.src.classify.simple] means we are supposed to have "src/ica/example/src/classify/simple.clj".

**Comment by dhk465** [comment]
I am going to integrate simple into our src.

**Comment by dhk465** [comment]
I found the actual problem: the namespace of simple.clj was not changed to ica.simple.
It was classify.siimple instead.
