### ISSUE TITLE
[BUG]-Bad commit on tester

### ISSUE THREAD

**Issue by ilyassakhanov** [dhk465/symbolic_comp_one#33]
**Describe the bug**
A tester branch is not working and it is my fault.

**To Reproduce**
1. Go to tester branch
2. Do "lein run" 
3. Enjoy the error message

**Original intention of my commit**
I wanted to complete one of the steps in issue #29, which is "Keep 80 characters per line ". Obviously, it was not successful and now the tester branch in not working.

**Help?**
If anyone can rollback the last commit on tester, please do it.
**Desktop (please complete the following information):**
 - Leiningen Version [e.g. 2.0.0]

** List of Dependencies **
- Dependency and Version [e.g. Cortex 1.9.3]
.

**Comment by dhk465** [comment]
@ilyassakhanov Can you give us the log?

**Comment by dhk465** [comment]
solved by commit [57d1454faace14c40d25809eaeda9ca6e2c1ae0c](https://github.com/dhk465/symbolic_comp_one/commit/57d1454faace14c40d25809eaeda9ca6e2c1ae0c)
