### ISSUE TITLE
[DISCUSSION] README changes

### ISSUE THREAD

**Issue by dhk465** [dhk465/symbolic_comp_one#35]
There are a few changes for README to be applied after the release of chatbot 2.0.

* [x] Fixes: the chatbot's name should be introduced.
* [x] Dependencies:
    * [x] Cortex
    * [x] Fruits Classification
* [x] Title from 'symbolic_comp' to a new name
* [x] Replace anything about first and second ICA with just "ICA"
* [x] Add an explanation of the chatbot's CNN architecture
* [x] Usages to be updated with a classification example
* [x] Limitations for classification e.g. 63% accuracy etc.
* [x] More references?

**Comment by Slemanof** [comment]
- Guidia name was used instead of "Chatbot"

- Title changed to "Guidia chatbot 2.0"

- ICA instead of first and second ICA

**Comment by dhk465** [comment]
CNN description was added to the github page rather than the readme
